owner: ryanda
repo: web-upptime

sites:
  - name: Jalan Damai
    url: http://jalandamai.org
  - name: Damailah Indonesiaku
    url: https://damailahindonesiaku.net
  - name: Duta Damai
    url: http://dutadamai.id

status-website:
  baseUrl: /web-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WebUpptime
  introTitle: "**bla bla bla**"
  introMessage: This is a sample status page
  navbar:
    - title: Status
      href: /
    - title: Repo
      href: https://github.com/$OWNER/$REPO
